### ISSUE TITLE
Menu disappears, possibly due to vanilla elevation step tool

### ISSUE THREAD

**Issue by pinkiepanda** [klyte45/CS-FineRoadTool#8]
![image](https://user-images.githubusercontent.com/18537474/121464509-fb5be580-c981-11eb-823e-41441d0907a1.png)

I'm not really sure how or what is causing this, but at a random point while playing the vanilla elevation step tool will reappear on the toolbar, and that seems to coincide with the FRT menu closing itself every time you click to lay a road, or click the tool icon itself.
To bring the menu back you have to back out (esc) of the road menu, then open it again.

Reloading the game will temporarily fix the issue, until the vanilla elevation step decides to reassert itself for some reason, sometimes after a few minutes, sometimes after 4 hours.

**Comment by YosypC** [comment]
I also have this problem.

**Comment by kevinlaw91** [comment]
This bug will show up in every of my playing session. ~~I have FPS Booster mod enabled, not sure if Picker or that is the culprit~~.

UPDATE:
Mods recently interacted with when this bug happens:
- FPS Booster
- Picker
- Network Multitool
- Node Controller Renewal

Interesting points that I found:
- When the bug is triggered
  - FRT and elevation button splits like shown in the screenshot above.
  - Doing any of these will hide the FRT button and FRT tool window
    - Click the FRT button (button will be gone as well as the window)
    - Elevation keys (+, -, reset)
    - Change road building mode
    - Drag elevation step slider
    - Toggle straight slope
  - Vanilla elevation button will still be visible after any of the actions.
  - Interact with FR anarchy buttons works perfectly, does not hide the FRT button and FRT tool window
  - Click road builder tool to have it activated...
    - Clicking an end node to continue building will trigger the disappear bug
  - When the UI disappeared, clicking other UI buttons such as Node Controller in UUI or Picker or etc. will make the UI re-appears.
- Road asset [UK road project](https://steamcommunity.com/sharedfiles/filedetails/?id=1601040013) triggered the bug for me many times (esp. the small road 2 Lane, 2 Way, 15m with Parking, icon has a "Suburbs" tag), not sure if there's a link between this.

**Comment by kevinlaw91** [comment]
Ending of the log when the bug triggers:

[NodeController] Enable tool
[NodeController] Disable tool
[NetworkMultitool] Enable tool

[NodeController] Disable tool
[Fine Road Tool 2.0.4] Deactivated 
    at FineRoadTool.FineRoadTool.Deactivate()

   at FineRoadTool.FineRoadTool.FineRoadTool.FineRoadTool.FpsBoosterUpdate_Patch0(FineRoadTool.FineRoadTool )

   at BehaviourUpdater.Utils.SafelyIterableList`1[[UnityEngine.MonoBehaviour, UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].CallUpdate()

   at BehaviourUpdater.Updater.Update()(x25)
[Fine Road Tool 2.0.4] Tool button parent changed: OptionsBar
[Fine Road Tool 2.0.4] Deactivated 
    at FineRoadTool.FineRoadTool.Deactivate()

   at FineRoadTool.FineRoadTool.FineRoadTool.FineRoadTool.FpsBoosterUpdate_Patch0(FineRoadTool.FineRoadTool )

   at BehaviourUpdater.Utils.SafelyIterableList`1[[UnityEngine.MonoBehaviour, UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].CallUpdate()

   at BehaviourUpdater.Updater.Update()

**Comment by kevinlaw91** [comment]
Sometimes the bug will miraculously "heal" by itself. When that happens, this is the log.
But after playing for some amount of time the bug will reappears

[NodeController] Enable tool
[NodeController] Disable tool
[Fine Road Tool 2.0.4] Deactivated 
    at FineRoadTool.FineRoadTool.Deactivate()

   at FineRoadTool.FineRoadTool.FineRoadTool.FineRoadTool.FpsBoosterUpdate_Patch0(FineRoadTool.FineRoadTool )

   at BehaviourUpdater.Utils.SafelyIterableList`1[[UnityEngine.MonoBehaviour, UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].CallUpdate()

   at BehaviourUpdater.Updater.Update()(x54)
[Fine Road Tool 2.0.4] Tool button parent changed: ElevationStep
[Fine Road Tool 2.0.4] Deactivated 
    at FineRoadTool.FineRoadTool.Deactivate()

   at FineRoadTool.FineRoadTool.FineRoadTool.FineRoadTool.FpsBoosterUpdate_Patch0(FineRoadTool.FineRoadTool )

   at BehaviourUpdater.Utils.SafelyIterableList`1[[UnityEngine.MonoBehaviour, UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].CallUpdate()

   at BehaviourUpdater.Updater.Update()
[NodeController] Enable tool
[NodeController] Disable tool
[NetworkMultitool] Enable tool
[NetworkMultitool] Disable tool

**Comment by dsedivec** [comment]
FYI: Easiest way to fix this for me has been to build some other kind of network.  If I'm building roads and elevation disappears, I build some railroad, delete it, then switch back to road.  If it disappears while I'm building railroad, I build some road and delete it, then back to railroad.

**Comment by klyte45** [comment]
This mod is being rebuilt by community. Wait for news soon!
